name: CI - Code Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code
